### PR TITLE
chore: Bump build:gradle to 2.3.0

### PR DESCRIPTION
**Pull request by cryptoumit**
Bump gradle to `2.3.0` as maven doesn't seem to have `2.2.3` anymore

Thread:
https://exodusio.slack.com/archives/C04AZNR9LN6/p1723714262798019?thread_ts=1723709911.817519&cid=C04AZNR9LN6

### CODE REVIEW

**Review by andrejborstnik — APPROVED** [review]
utACK

**Review by mariosvlad — APPROVED** [review]
utACK

**Review by gutenye — APPROVED** [review]
utACK

**Comment by gutenye** [comment]
@cryptoumit We have [this](https://github.com/ExodusMovement/exodus-mobile/pull/21301) now, can you revert this one?

**Comment by cryptoumit** [comment]
@gutenye Here's the revert: https://github.com/ExodusMovement/react-native-threads/pull/5

**Comment by mvayngrib** [comment]
i thought we were using the `exodus` branch in this repo, should we cherry-pick this there?

**Comment by gutenye** [comment]
@mvayngrib There's no `exodus` branch in this repo. We don't need this PR anymore, we already have a patch in react-native-base

**Comment by mvayngrib** [comment]
@gutenye there is, see the history there https://github.com/ExodusMovement/react-native-threads/tree/exodus

**Comment by gutenye** [comment]
@mvayngrib Can you make that branch as the default? I don't have the privileges

**Comment by mvayngrib** [comment]
don't have the powers, @andrejborstnik are you admin here?

**Comment by andrejborstnik** [comment]
> don't have the powers, @andrejborstnik are you admin here?

You are an admin now :)

**Comment by mvayngrib** [comment]
haha, a game of admin tag, eh?

**Comment by mvayngrib** [comment]
@gutenye `exodus` is now the default branch

**Pull request merged**
